# Generated by Django 4.1 on 2022-10-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="exercise_time",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="first_notification_time",
            field=models.DateTimeField(
                null=True, verbose_name="first notification time"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="last_notification_time",
            field=models.DateTimeField(
                null=True, verbose_name="last notification time"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="total_awake_time",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="water_amount_per_day",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="water_amount_per_hour",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="weight",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
