# Generated by Django 4.1 on 2022-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0002_userinfo_exercise_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="first_notification_time",
            field=models.TimeField(null=True, verbose_name="first notification time"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="last_notification_time",
            field=models.TimeField(null=True, verbose_name="last notification time"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="total_awake_time",
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="water_amount_per_hour",
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
