# Generated by Django 4.1 on 2022-10-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0003_alter_userinfo_first_notification_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo", old_name="total_awake_time", new_name="total_hours",
        ),
    ]
