# Generated by Django 4.1 on 2022-10-19 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aquaholic", "0004_rename_total_awake_time_userinfo_total_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="intake_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="intake",
            name="user_drinks_amount",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="intake",
            name="user_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="expected_amount",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="schedule",
            name="notification_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="notification_time",
            field=models.DateTimeField(null=True, verbose_name="notification time"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="user_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
