# Generated by Django 4.1 on 2022-10-23 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aquaholic", "0005_intake_intake_date_intake_user_drinks_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="intake",
            name="user_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aquaholic.userinfo",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="user_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aquaholic.userinfo",
            ),
        ),
    ]
