# Generated by Django 4.1 on 2022-10-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0006_userinfo_user_alter_intake_user_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="notify_token",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
