<<<<<<< HEAD
# Generated by Django 4.1 on 2022-10-27 19:47
=======
# Generated by Django 4.1 on 2022-10-27 16:43
>>>>>>> 62a736ab69e3db7dca29259010847e04ebc62e17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0007_userinfo_notify_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="exercise_time",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
