# Generated by Django 4.1 on 2022-10-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0008_alter_userinfo_exercise_time_alter_userinfo_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="water_amount_per_hour",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
