# Generated by Django 4.1 on 2022-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0010_alter_userinfo_water_amount_per_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="user_drinks_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="expected_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="exercise_time",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="total_hours",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="water_amount_per_day",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="water_amount_per_hour",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="userinfo", name="weight", field=models.FloatField(default=0),
        ),
    ]
