# Generated by Django 4.1 on 2022-10-28 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0011_alter_intake_user_drinks_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="first_notification_time",
            field=models.TimeField(
                default=datetime.time(8, 0), verbose_name="first notification time"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="last_notification_time",
            field=models.TimeField(
                default=datetime.time(22, 0), verbose_name="last notification time"
            ),
        ),
    ]
