# Generated by Django 4.1 on 2022-10-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0012_alter_userinfo_first_notification_time_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Schedule", new_name="ScheduleModel",),
    ]
