# Generated by Django 4.1 on 2022-10-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0013_rename_schedule_schedulemodel"),
    ]

    operations = [
        migrations.RenameModel(old_name="ScheduleModel", new_name="Schedule",),
    ]
