# Generated by Django 4.1 on 2022-11-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0014_rename_schedulemodel_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="notification_time",
            field=models.TimeField(null=True, verbose_name="notification time"),
        ),
    ]
