# Generated by Django 4.1 on 2022-11-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0014_rename_schedulemodel_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_last",
            field=models.BooleanField(default=False),
        ),
    ]
