# Generated by Django 4.1 on 2022-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0015_alter_schedule_notification_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_last",
            field=models.BooleanField(default=False),
        ),
    ]
