# Generated by Django 4.1 on 2022-11-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0015_schedule_is_last"),
    ]

    operations = [
        migrations.RenameField(
            model_name="intake", old_name="intake_date", new_name="date",
        ),
        migrations.RenameField(
            model_name="intake", old_name="user_drinks_amount", new_name="total_amount",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="exercise_time",
            new_name="exercise_duration",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="expected_amount",
            field=models.IntegerField(default=0),
        ),
    ]
