# Generated by Django 4.1 on 2022-11-03 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0015_alter_intake_intake_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="intake_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 3, 22, 41, 19, 668691)
            ),
        ),
    ]
