# Generated by Django 4.1 on 2022-11-03 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0016_alter_intake_intake_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="intake_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 16, 10, 37, 786645, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
