# Generated by Django 4.1 on 2022-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0016_rename_intake_date_intake_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="time_interval",
            field=models.IntegerField(default=1),
        ),
    ]
