# Generated by Django 4.1 on 2022-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0016_schedule_is_last"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_first",
            field=models.BooleanField(default=False),
        ),
    ]
