# Generated by Django 4.1 on 2022-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0017_schedule_is_first"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="notification_time",
            field=models.DateTimeField(null=True, verbose_name="notification time"),
        ),
    ]
