# Generated by Django 4.1 on 2022-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0017_userinfo_time_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="water_amount_per_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="water_amount_per_hour",
            field=models.IntegerField(null=True),
        ),
    ]
