# Generated by Django 4.1 on 2022-11-03 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0018_alter_intake_intake_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="intake_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
