# Generated by Django 4.1 on 2022-11-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aquaholic", "0018_alter_schedule_notification_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="schedule", name="is_first",),
    ]
